spring:
  application:
    name: bungalow     
  cloud:
    config:
      uri: https://github.com/kaushiwicky/config-server-test:8888 
     
# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# HTTP Server
server:
  port: 2222   # HTTP (Tomcat) port
  
spring:
	data:
		mongodb:
			database:Forest-Bungalow
			
spring:
	data:
		:mongodb:
			host:localhost
spring:
	data:
		mongodb:
			port:27017
